apiVersion: apps/v1
kind: Deployment 
metadata:
  name: kubewatch-qyweapp
  namespace: kube-watch
  labels:
    app: wechat-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubewatch-qyweapp
  template:
    metadata:
      labels:
        app: kubewatch-qyweapp
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: kubewatch-qyweapp
          image: your-private-harbor-com/tools/kubewatch-qyweapp:latest #请修改为您自己的镜像地址
          imagePullPolicy: Always

